### ISSUE TITLE
Tweaks

### ISSUE THREAD

**Issue by georgeaf99** [DelegateIt/LandingWebsite#13]
Bugs:
- [x] The flag icon doesn't render when entering a number and refreshing the page

Improvements:
- [ ] Add a receipt message to the how it works conversation
- [x] Start each "how it works" bullet point w/ a verb for parallel structure (text is on Slack)
- [ ] Decrease picture height on mobile
- [ ] Lower title text so it centers in the part of screen not taken up by the navbar

![No Flag Icon](https://cloud.githubusercontent.com/assets/5133801/14400370/e429fdc0-fdbc-11e5-8fcf-cff6b5022d98.png)

**Comment by nathanchapman** [comment]
I'm not experiencing these issues. We'll look into the flag and scroll to top buttons this weekend.

**Comment by xuset** [comment]
The "The flag icon doesn't render when entering a number and refreshing the page" issue only occurs in firefox (at least for me); chrome works fine.

**Comment by nathanchapman** [comment]
@georgeaf99 @xuset Will you both please double check the flag not rendering issue? I don't see this on any browser or device..
if you still encounter it, please post the steps to reproduce the issue.

**Comment by nathanchapman** [comment]
I'll work on solving the rendering after refresh issue on firefox after the other issues have been patched

**Comment by georgeaf99** [comment]
I was having the same issue as Austin over the past day or two; however, the flag is rendering on Firefox now.

**Comment by nathanchapman** [comment]
I saw the issue with entering a number and refreshing while the number was still present (only in ff)
Just pushed a super simple fix. Checking this one off.

**Comment by georgeaf99** [comment]
@nathanchapman seems to work for me!

There is another issue where the validation doesn't work in real-time. You enter your number and the box stays red, then re-formats the number w/ parens & a dash, and finally validates it. 

Is the validation function running on a different thread?

**Comment by nathanchapman** [comment]
"then re-formats the number w/ parens & a dash"

Where do you see this? There's no reformatting in this plugin. They removed it due to the huge amount of overhead and inefficiencies with reformatting data as a user types.

The input box should stay red until a valid number is entered, and the user's input should never be reformatted at any point during their interaction.

**Comment by georgeaf99** [comment]
I did not enter the parenthesis (or the dash). They were automatically added.

Also, notice that the phone number is valid.

![Weird Input Box Behavior](https://cloud.githubusercontent.com/assets/5133801/14439292/15968b28-fff0-11e5-9d5c-25c8dd1aa8d7.png)

**Comment by nathanchapman** [comment]
What the fuck.
What device / browser / version?

I've tried ff, chrome, and safari on my laptop and haven't seen this happen. In fact, it's not even supported by the plugin. Maybe you have an extension (like skype or something) that's recognizing this as an "input:tel" and is automatically adding them. Either way, that number (with parens and dashes) **does** in fact validate if typed manually..

**Comment by georgeaf99** [comment]
Mac / ff / (Will check later)

I doubt is one of my plugins. How exactly is the verification being triggered? (When a character is entered, is it on a different thread or async function call)

**Comment by nathanchapman** [comment]
Verification =/= input modification. If you aren't typing the parentheses or dashes, then something is and that something is not the library. They wrote ~5 paragraphs on why they used to do that but don't anymore. I can't reproduce the auto typed symbols on any device/browser.
