### ISSUE TITLE
Text content is unreadable

### ISSUE THREAD

**Issue by georgeaf99** [DelegateIt/LandingWebsite#4]
The paragraph font size is too small to read and also is too verbose. We need to update the text to make it more concise and then scale up the font. 

Checklist:
- [ ] Decide what content is important
- [ ] Make the text more concise and clear
- [x] Remove "we do it all" & "we unlock time"
- [x] Increase the font size (on navbar as well)
- [x] Change the font for "we're pushing the envelope..."

**Comment by georgeaf99** [comment]
Perhaps "Delegate Now" should be "Order Now". I'm not sure if that would make it more understandable? I originally thought that "Delegate Now" was an application to be a delegator.

**Comment by nathanchapman** [comment]
@georgeaf99 Can I get some better text content from you or the marketing team? Mainly for the "vacations" section at the bottom.

**Comment by georgeaf99** [comment]
@nathanchapman Connor should be able to help rewrite the content
