### ISSUE TITLE
DelegateIt logo at the bottom of the page should be gold

### ISSUE THREAD

**Issue by georgeaf99** [DelegateIt/LandingWebsite#7]
The DelegateIt logo + name should always be gold or gold surrounded by white.

**Comment by nathanchapman** [comment]
I'll need the logo assets in a png file format to do this. The only file type I see is svg, which can't be edited easily with CSS or Photoshop.

**Comment by georgeaf99** [comment]
@nathanchapman I don't know where to find that... Can you talk to Reubens or maybe @bwernsman has it?
